name: dnl
version: '19'
author: HexNowLoading
description: A dungeon made by Hex

data_pack:
  load: [src]
  zipped: false
  pack_format: 12

resource_pack:
  load: [src]
  zipped: false
  pack_format: 13

output: 'build'

require:
  - bolt
  - bolt_expressions
  - reapermc

pipeline:
  - mecha
  - plugins.remove_empty_files
  - beet.contrib.copy_files
  - beet.contrib.worldgen

meta:
  bolt:
    entrypoint:
      - dnl:*
  copy_files:
    resource_pack:
      assets: "src/assets/*.*"
      assets/minecraft/optifine: "src/assets/minecraft/optifine/*.*"
      assets/minecraft/optifine/anim: "src/assets/minecraft/optifine/anim/*.*"
      assets/minecraft/optifine/cit/armor: "src/assets/minecraft/optifine/cit/armor/*.*"
      assets/minecraft/optifine/random/entity/ghast: "src/assets/minecraft/optifine/random/entity/ghast/*.*"
  dnl:
    namespace: 'dnl'
    cmd_namespace: 'cmd'
    datapack_version: 19
  item:
    ancient_bow: 1
    ancient_bow_red: 2
    ancient_bow_blue: 3
    ancient_bow_yellow: 4
    fleshbone_bow: 5
    ominous_crossbow: 6
    royal_ominous_crossbow: 7
    broken_bow: 8
    frost_watcher_bow: 9
  
    ancient_axe: 1001
    ancient_sword: 1002
    fleshbone_sword: 1003
    knightly_sword: 1004
    ominous_axe: 1005
    royal_ominous_axe: 1006
    poison_rapier: 1007
    oasis_trident: 1008

    ancient_pickaxe: 2001
    spawner_breaker: 2002
    
    crown_of_olympus: 3001
    golem_heart_armor: 3002
    heavy_iron_armor: 3003
    
    checkpoint_player_head: 4001
    diamond_upgrade: 4002
    dungeon_clock: 4003
    olympus_key: 4004
    ominous_horn: 4005
    plains_castle_key: 4006
    spell_breaker: 4007
    golem_gift: 4008

    forbidden_apple: 5001
    forbidden_berries: 5002
    forbidden_melon: 5003
    forbidden_golden_apple: 5004
    honey_potion: 5005
    royal_honey_potion: 5006
    pumpkin_treat: 5007

    ancient_shield: 6001
    pumpkin_shield: 6002

    hivenest: 7001
    sinkhole: 7002
    hunter_grave: 7003
    deep_oasis: 7004
    cleric_hideout: 7005
    railway_outpost: 7006
    watcher_camp: 7007
    crawler_lair: 7008
    gallery_of_illusion: 7009
    forgotten_field: 7010
    temple_of_tears: 7012
    olympus: 7015
    plains_castle: 7016
    plains_labyrinth: 7017
    plains_pillager_camp: 7018
    hivenest_boss: 7101

    rusted_iron_fragment: 8001
    honeycomb_ingot: 8002
    knightly_sword_fragment: 8003
    old_letter: 8004
    poppy_of_memories: 8005
    ominous_emerald: 8006
    sharpened_bone: 8007
    spawner_fragment: 8008
    staring_flesh: 8009
    nobility: 8010

    music_disc_alpha: 9001
    music_disc_meirah: 9002
    music_disc_bees: 9003
    music_disc_woodland_fountain: 9004
    music_disc_welcome_to_hell: 9005
    music_disc_jack_and_lantern: 9006

    death_star: 9999